routes/web.php
<?php

use App\Http\Controllers\CategoryVideoController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\DislikeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\VideoController;
use App\Http\Middleware\CheckVerifyEmail;
use App\Jobs\Otp;
use App\Jobs\ProcessVideo;
use App\Mail\VerifyEmail;
use App\Models\User;
use App\Services\FFmpegAdapter;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [IndexController::class,'index'])->name('index');


Route::get('/videos/create',[VideoController::class, 'create'])->middleware(['emailVerify'])->name('videos.create');
Route::post('/videos',[VideoController::class, 'store'])->name('videos.store');
Route::get('/videos/{video}', [VideoController::class, 'show'])->name('videos.show');
Route::get('/videos/{video}/edit',[VideoController::class,'edit'])->name('videos.edit');
Route::post('/videos/{video}',[VideoController::class,'update'])->name('videos.update');

Route::get('/categories/{category:slug}/videos',[CategoryVideoController::class, 'index'])->name('categories.videos.index');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::post('/videos/{video}/comments',[CommentController::class, 'store'])->name('comments.store');
Route::get('{likeable_type}/{likeable_id}/like',[LikeController::class, 'store'])->middleware(['auth'])->name('likes.store');
Route::get('{likeable_type}/{likeable_id}/dislike',[DislikeController::class, 'store'])->middleware(['auth'])->name('dislikes.store');





require __DIR__ . '/auth.php';

app/Models/Comment.php
<?php

namespace App\Models;

use App\Models\Traits\Likeable;
use Hekmatinasser\Verta\Verta;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use HasFactory,Likeable;
    protected $fillable = ['body', 'user_id'];

    public function video()
    {
        return $this->belongsTo(Video::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getCreatedAtInHumanAttribute()
    {
        return (new Verta($this->created_at))->formatDifference();
    }

}

app/Models/Traits/Likeable.php
<?php

namespace App\Models\Traits;


use App\Models\Like;
use App\Models\User;

trait Likeable
{

    public function likes()
    {
        return $this->morphMany(Like::class, 'likeable');
    }

    public function getLikesCountAttribute()
    {
        return $this->likes()
            ->where('vote',1)
            ->count();
    }

    public function getDislikesCountAttribute()
    {
        return $this->likes()
            ->where('vote',-1)
            ->count();
    }

    public function likedBy(User $user)
    {
        if ($this->isLikedBy($user)) return;
        return $this->likes()->create([
            'vote' => 1,
            'user_id' => $user->id
        ]);
    }

    public function dislikedBy(User $user)
    {
        if ($this->isDislikedBy($user)) return;
        return $this->likes()->create([
            'vote' => -1,
            'user_id' => $user->id
        ]);
    }

    public function isLikedBy(User $user)
    {
        return $this->likes()
        ->where('vote',1)
        ->where('user_id',$user->id)
        ->exists();

    }

    public function isDislikedBy(User $user)
    {
        return $this->likes()
        ->where('vote',-1)
        ->where('user_id',$user->id)
        ->exists();

    }
}

app/Models/Video.php
<?php

namespace App\Models;

use App\Filters\VideoFilters;
use App\Models\Traits\Likeable;
use Hekmatinasser\Verta\Verta;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class Video extends Model
{
    use HasFactory,Likeable;
    protected $perPage = 16;

    protected $fillable = [
        'name', 'path', 'thumbnail' , 'slug','length', 'description','category_id'
    ];

    public function getRouteKeyName()
    {
        return ('slug'); // TODO: Change the autogenerated stub
    }

    public function getLengthInHumanAttribute(): string
    {
        return gmdate("i:s" , $this->length);
    }

    public function getCreatedAtAttribute($value): string
    {
        return (new Verta($value))->formatDifference();
    }

    public function relatedVideos(int $count = 6)
    {
        return $this->category->getRandomVideos($count);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getCategoryNameAttribute()
    {
        return $this->category?->name;
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getOwnerNameAttribute()
    {
        return $this->user?->name;
    }

    public function getOwnerAvatarAttribute()
    {
        return $this->user?->gravatar;
    }

    public function comments()
    {
        return $this->hasMany(Comment::class)->orderBy('created_at', 'desc');
    }

    public function getVideoUrlAttribute()
    {
        return '/storage/' . $this->path;
    }

    public function getVideoThumbnailAttribute()
    {
        return '/storage/' . $this->thumbnail;
    }

    public function scopeFilter( Builder $builder , array $params) 
    {
        return (new VideoFilters($builder))->apply($params);
    }

    
}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;




use App\Http\Middleware\CheckVerifyEmail;
use App\Http\Requests\StoreVideoRequest;
use App\Http\Requests\UpdateVideoRequest;
use App\Models\Category;
use App\Models\Video;
use App\Services\FFmpegAdapter;
use App\Services\VideoService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;

class VideoController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Video::class , 'video');
    }
    public function index()
    {
        $videos = Video::all();
        return $videos;
    }

    public function create()
    {
        $categories = Category::all();
        return view('videos.create', compact('categories'));
    }

    public function store(StoreVideoRequest $request)
    {
        (new VideoService)->create($request->user(),$request->all());
        return redirect()->route('index')->with('alert',__('messages.success'));
    }

    public function show(Request $request, Video $video)
    {
        $video->load('comments.user');
        return view('videos.show', compact('video'));
    }

    public function edit(Video $video)
    {
        
        $categories = Category::all();
        return view('videos.edit', compact('video','categories'));
    }

    public function update(UpdateVideoRequest $request, Video $video)
    {
        (new VideoService)->update($video, $request->all());
        return redirect()->route('videos.show', $video->slug)->with('alert',__('messages.video_edited'));
    }
}

resources/views/videos/create.blade.php
@extends('layout')
@section('content')
    <div id="upload">
        <div class="row">
            <x-validation-errors></x-validation-errors>
            <!-- upload -->
            <div class="col-md-8">
                <h1 class="page-title"><span>آپلود</span> فیلم</h1>
                <form action="{{route('videos.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <label>@lang('videos.name')</label>
                            <input name="name" type="text" class="form-control" value="{{old("name")}}" placeholder="@lang('videos.name')">
                        </div>
                        <div class="col-md-6">
                            <label>نام یکتا</label>
                            <input type="text" name="slug" class="form-control" value="{{old("slug")}}" placeholder="نام یکتا">
                        </div>
                        <div class="col-md-6">
                            <label>آدرس ویدیو</label>
                            <input type="file" name="file" class="form-control">
                        </div>
                        <div class="col-md-6">
                            <label>دسته بندی</label>
                            <select class="form-control" name="category_id" id="category">
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}"> {{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-12">
                            <label>توضیحات</label>
                            <textarea class="form-control" name="description" rows="4"  placeholder="توضیح">{{old("description")}}</textarea>
                        </div>
                        <div class="col-md-2">
                            <button type="submit" id="contact_submit" class="btn btn-dm">ذخیره</button>
                        </div>
                    </div>
                </form>
            </div><!-- // col-md-8 -->
            <div class="col-md-4">
                <a href="#"><img src="{{ asset('img/upload-adv.png') }}" alt=""></a>
            </div><!-- // col-md-8 -->
            <!-- // upload -->
        </div><!-- // row -->
    </div>
@endsection

resources/views/videos/edit.blade.php
@extends('layout')
@section('content')
    <div id="upload">
        <div class="row">
            <x-validation-errors></x-validation-errors>
            <!-- upload -->
            <div class="col-md-8">
                <h1 class="page-title"><span>آپلود</span> فیلم</h1>
                <form action="{{ route('videos.update',$video->slug) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <label>@lang('videos.name')</label>
                            <input name="name" type="text" class="form-control" value="{{$video->name}}" placeholder="@lang('videos.name')">
                        </div>
                        <div class="col-md-6">
                            <label>نام یکتا</label>
                            <input type="text" name="slug" class="form-control" value="{{$video->slug}}" placeholder="نام یکتا">
                        </div>
                        <div class="col-md-6">
                            <label>آدرس ویدیو</label>
                            <input type="file" name="file" id="" class="form-control">
                        </div>
                        <div class="col-md-6">
                            <label>دسته بندی</label>
                            <select class="form-control" name="category_id" id="category">
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}" {{$category->id == $video->category_id ? 'selected' :''}}> {{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-12">
                            <label>توضیحات</label>
                            <textarea class="form-control" name="description" rows="4"  placeholder="توضیح">{{$video->description}}</textarea>
                        </div>
                        <div class="col-md-2">
                            <button type="submit" id="contact_submit" class="btn btn-dm">ذخیره</button>
                        </div>
                    </div>
                </form>
            </div><!-- // col-md-8 -->
            <div class="col-md-4">
                <a href="#"><img src="{{ asset('img/upload-adv.png') }}" alt=""></a>
            </div><!-- // col-md-8 -->
            <!-- // upload -->
        </div><!-- // row -->
    </div>
@endsection

resources/views/videos/index.blade.php
@extends('layout')
@section('content')
    <form class="mt-5" action="#" method="get">
        <div class="row">
            <div class="form-group col-md-3">
                <label for="inputCity">ترتیب براساس</label>
                <select class="form-control" name="sortBy">
                    <option {{ request()->query('sortBy') == 'created_at' ? 'selected' : '' }} value="created_at">جدیدترین</option>
                    <option {{ request()->query('sortBy') == 'like' ? 'selected' : '' }} value="like">محبوب ترین</option>
                    <option {{ request()->query('sortBy') == 'length' ? 'selected' : '' }} value="length">مدت زمان ویدیو</option>
                </select>
            </div>
            <div class="form-group col-md-3">
                <label for="inputCity">مدت زمان</label>
                <select id="inputCity" class="form-control" name="length">
                    <option {{ request()->query('length') == null ? 'selected' : '' }} value = "" >همه</option>
                    <option {{ request()->query('length') == 1 ? 'selected' : '' }} value="1">کمتر از یک دقیقه</option>
                    <option {{ request()->query('length') == 2 ? 'selected' : '' }} value="2">تا ۵ دقیقه ۱</option>
                    <option {{ request()->query('length') == 3 ? 'selected' : '' }} value="3">بیشتر از ۵ دقیقه</option>

                </select>
            </div>
            <input type="hidden" name="q" value="{{request()->query('q')}}">
            <div class="form-group col-md-3" style="margin-top: 29px">
                <button type="submit" class= "btn btn-primary">فیلتر</button>
            </div>
        </div>
    </form>

    <h1 class="new-video-title"><i class="fa fa-bolt"></i>{{$title}}</h1>
    <div class="row">
        @foreach($videos as $video)
            <x-video-box :video="$video"></x-video-box>
        @endforeach
    </div>
    <div class="text-center" dir="ltr">
        {{ $videos->links() }}
    </div>
@endsection

resources/views/videos/show.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <!-- Watch -->
        <div class="col-md-8">
            <div id="watch">
                <x-validation-errors></x-validation-errors>

                <!-- Video Player -->
                <h1 class="video-title">{{$video->name}}</h1>
                <div class="video-code">
                    <video controls style="height: 100%; width: 100%;">
                        <source
                            src="{{$video->video_url}}"
                            type="video/mp4">
                    </video>
                </div><!-- // video-code -->
                <div>
                    <p>
                        {{$video->description}}
                    </p>
                </div>

                <div class="video-share">
                    <ul class="like">
                        <li><a class="deslike" href="{{route('dislikes.store',['likeable_type'=>'video', 'likeable_id'=> $video])}}">{{$video->dislikes_count}} <i class="fa fa-thumbs-down"></i></a></li>
                        <li><a class="like" href="{{route('likes.store',['likeable_type'=>'video', 'likeable_id'=> $video])}}">{{$video->likes_count}} <i class="fa fa-thumbs-up"></i></a></li>
                    </ul>
                    <ul class="social_link">
                        <li><a class="facebook" href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        </li>
                        <li><a class="youtube" href="#"><i class="fa fa-youtube-play"
                                                           aria-hidden="true"></i></a></li>
                        <li><a class="linkedin" href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                        </li>
                        <li><a class="google" href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                        </li>
                        <li><a class="twitter" href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                        </li>
                        <li><a class="rss" href="#"><i class="fa fa-rss" aria-hidden="true"></i></a></li>
                    </ul><!-- // Social -->
                </div><!-- // video-share -->
                <!-- // Video Player -->


                <!-- Chanels Item -->
                <div class="chanel-item">
                    <div class="chanel-thumb">
                        <a href="#"><img src="{{$video->owner_avatar}}" alt=""></a>
                    </div>
                    <div class="chanel-info">
                        <a class="title" href="#">{{$video->owner_name}}</a>
                        <span class="subscribers">436,414 اشتراک</span>
                    </div>
                    <a href="#" class="subscribe">اشتراک</a>
                </div>
                <!-- // Chanels Item -->


                <!-- Comments -->
                <div id="comments" class="post-comments">
                    <h3 class="post-box-title"><span>{{$video->comments->count()}}</span> نظرات</h3>
                    <ul class="comments-list">
                        @foreach($video->comments as $comment)
                        <li>
                            <div class="post_author">
                                <div class="img_in">
                                    <a href="#"><img src="{{$comment->user->gravatar}}" alt=""></a>
                                </div>
                                <a href="#" class="author-name">{{$comment->user->name}}</a>
                                <time datetime="2017-03-24T18:18">{{$comment->created_at_in_human}}</time>
                                <a class="deslike mr-5" style="coler: #aaaaaa"
                                   href="{{route('dislikes.store',['likeable_type'=>'comment', 'likeable_id'=> $comment])}}">{{$comment->dislikes_count}}<i class="fa fa-thumbs-down"></i> </a>
                                <a class="like mr-5" style="coler: #66c0c2"
                                   href="{{route('likes.store',['likeable_type'=>'comment', 'likeable_id'=> $comment])}}">{{$comment->likes_count}}<i class="fa fa-thumbs-up"></i> </a>
                            </div>
                            <p>{{$comment->body}}</p>


                        </li>
                        @endforeach
                    </ul>


                    <h3 class="post-box-title">ارسال نظرات</h3>
                    <form action="{{route('comments.store', $video)}}" method="post">
                        @csrf
                        <textarea class="form-control" name="body" rows="8" id="Message" placeholder="پیام"></textarea>
                        <button  id="contact_submit" class="btn btn-dm">ارسال پیام</button>
                    </form>
                </div>
                <!-- // Comments -->


            </div><!-- // watch -->
        </div><!-- // col-md-8 -->
        <!-- // Watch -->

        <!-- Related Posts-->
        <div class="col-md-4">
            <x-related-videos :video="$video"></x-related-videos>
        </div><!-- // col-md-4 -->
        <!-- // Related Posts -->
    </div><!-- // row -->
@endsection